### ISSUE TITLE
fantastic app.. can you get data for dates before you started?

### ISSUE THREAD

**Issue by jfkdcman** [Samuelincoom/Ghana_Covid-19_native_Android_App#1]
fantastic app.. can you get data for dates before you started the project on april 10th?

**Comment by Samuelincoom** [comment]
they do not give out previous dates on their official site..  As a matter of fact they don't even have an API lolz..
Probably only the Workers there at GHS will have the previous data.... but don't worry, cos after today the bot i created yesterday will keep all the data so we will all have a proper curve to analize in 7 days time
